# Generated by Django 6.0.2 on 2026-02-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="published_data",
            new_name="pub_date",
        ),
    ]
